---
dependency:
  name: galaxy

driver:
  # Specifies the driver that should be used. Podman should also work
  name: docker

lint: |
  yamllint .
  ansible-lint --exclude=molecule/default/verify.yml -x 106

platforms:
  # Set name and hostname
  - name: ns1
    groups:
      - dns
    hostname: ns1
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    tty: true
    environment:
      container: docker

  - name: ns2
    hostname: ns2
    groups:
      - dns
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    tty: true
    environment:
      container: docker

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_legacy_silent
      callback_whitelist: profile_tasks
    ssh_connection:
      pipelining: true

# Runs the verify.yml playbook
verifier:
  name: ansible
